apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: my-java-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: my-java-app-image
  policy:
    semver:
      range: "*"
