apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: my-java-app-automation
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: my-java-app-repo
  git:
    checkout:
      ref:
        branch: main
    commit:
      authorName: Flux
      authorEmail: flux@example.com
    push:
      branch: main
  update:
    path: ./
